#!/usr/bin/env bash
#A script that creates a file containing its PID displays terminate and deletes
script="/var/run/myscript.pid"
echo $$ > "$script"
trap 'echo "I hate the kill command;rm "$cript"; exit' SIGTERM SIGQUIT
while ;: do echo 'To infinity and beyond'; sleep 2;done
