#!/usr/bin/env bash
#A script that creates a file containing its PID displays terminate and deletes
sudo bash -c "echo $$ > /var/run/myscript.pid"
trap 'echo "Y U no love me?!"'SIGINT
trap "sudo rm -f /var/run/myscript.pid; exit " SIGQUIT
trap "sudo rm -f /var/run/myscript .pid; echo I hate the kill  ommand; exit SIGTERM
while ;: do echo 'To infinity and beyond '; sleep 2;done
